language: node_js
node_js:
- "11"
- "10"

before_install:
- export CXX="g++-4.9" CC="gcc-4.9"
- npm install -g codecov

before_deploy:
- lerna bootstrap
- lerna run build

after_success:
  - codecov
after_failure:
  - codecov

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.9
